config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'likes/create/:id', to: 'likes#create', as: 'likes_create'
  get '/users/:user_id/posts', to: 'posts#index', as: 'user_posts'
  get '/users/:user_id/posts/:id', to: 'posts#show', as: 'user_post'
  get '/users', to: 'users#index', as: 'users'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/posts/new', to: 'posts#new', as: 'post_new'
  post '/posts/new', to: 'posts#create', as: 'post_create'
  get '/comments/new/:id', to: 'comments#new', as: 'comments_new'
  post '/comments/create', to: 'comments#create', as: 'comment_create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :text, presence: true
  after_create :update_posts_counter

  private

  def update_posts_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_create :update_posts_counter

  private

  def update_posts_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :comments
  has_many :likes

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  after_create :update_user_counter

  def recent_comments
    comments.includes(:user).order(created_at: :desc).limit(5)
  end

  private

  def update_user_counter
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: :author_id
  has_many :comments, foreign_key: :user_id
  has_many :likes, foreign_key: :user_id

  validates :name, presence: true
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :photo, :bio, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :photo, :bio, :email, :password, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    @post = Post.find(params[:id])
    @current_user = current_user
  end

  def create
    @comment = Comment.new user: current_user, post_id: params[:post_id], text: params[:text]
    if @comment.save
      redirect_to "/users/#{@comment.post.author_id}/posts/#{@comment.post.id}"
    else
      render "/comments/new/#{@comment.post.id}", status: :unprocessable_entity
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.create user: current_user, post_id: params[:id]
    redirect_to "/users/#{@like.post.author_id}/posts/#{@like.post_id}"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.includes(:comments).find(params[:id])
    @comments = @post.comments
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new author: current_user, title: params[:title], text: params[:text], comments_counter: 0,
                     likes_counter: 0
    if @post.save
      redirect_to "/users/#{current_user.id}/posts/#{@post.id}"
    else
      render :new, status: :unprocessable_entity
      puts '********invalid post*********'
      puts @post.errors.messages
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.recent_posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comment#create</h1>
<p>Find me in app/views/comment/create.html.erb</p>

app/views/comments/new.html.erb
<%= content_tag :h1, 'New Comment for Post:' %>

<%= content_tag :h2, @post.title %>

<%= form_with url: :comment_create do |form|%>
  <%= form.hidden_field :user_id, value: @current_user.id  %>
  <%= form.hidden_field :post_id, value: @post.id%>
  <%= form.label :text, 'Content: '%>
  <%= form.text_area :text %>
  <%= form.submit %>
<% end %>

<% @comment.errors.messages.each do |key,message| %>
  <%= content_tag :h4, "#{key}  #{message}" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar">
      <%if current_user%>
        <img src="<%= current_user.photo %>" alt="User Photo" class="navbar-user-photo">  
        <%= content_tag :h2, "Welcome #{current_user.name}", class: "navbar-link" %>
        <%= link_to 'Sign out', destroy_user_session_path, data: { turbo_method: :delete }, class: "navbar-link " %>
        <%= link_to 'Edit Profile', edit_user_registration_path, method: :get, class: "navbar-link" %>
        <%= link_to 'New post', post_new_path, class: "navbar-link" %>
        <% else %>
        <%= link_to 'Sign in', new_user_session_path, class: "navbar-link" %>
      <% end %>
        <%= link_to 'Home', '/', class: "navbar-link" %>
      <div>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/layouts/user_card.erb
      <td>
        <%= image_tag user.photo,
        alt: "User Photo", width: "100" %>
      </td>
      <td>
        <%= content_tag :h2, user.name %>
        <%= content_tag :p, "Number of posts: #{user.posts_counter}" %>
      </td>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/posts/index.html.erb
<div class="user-item">
  <%= image_tag @user.photo,alt: "User Photo", class:"user-photo" %>
  <div class="user-info">
    <%= content_tag :h2, @user.name %>
    <%= content_tag :p, "Number of posts: #{@user.posts_counter}" %>
  </div>
</div>

<%= content_tag :h4, 'ALL POSTS', class:"post-list-title"%>
    
<% @posts.each do |post|%>
  <div class="user-bio">
    <a class="post-title label-link" href="<%= user_post_path(@user, post) %> ">
      <%= content_tag :h4, post.title %>
    </a>  
    <%= content_tag :p, post.text.truncate(100)%>
    <p>
      <%= content_tag :small, "Comments: #{post.comments_counter}, Likes: #{post.likes_counter}" %>
    </p>
      
    <div class='comments-box'>
      <%= content_tag :h5, 'Recent Comments', class:"recent-comments-header" %>          
      <% post.recent_comments.each do |comment|%>
        <p class="comment-item">
          <%= content_tag :span, "#{comment.user.name}:  ", class:"comment-author-name"%>
          <%= content_tag :span, comment.text %>
        </p>
      <% end %>
    </div>
  </div>      
     
    <%end%>
    <%= link_to 'Pagination', "/users/#{@user.id}/posts" %>

app/views/posts/new.html.erb
<%= content_tag :h1, 'New Post' %>

<%= form_with do |form| %>
  <%= form.label :title, 'Title: ' %>
  <%= form.text_field :title %>
  <%= form.label :text, 'Content: ' %>
  <%= form.text_field :text %>
  <%= form.submit %>
<% end %>

<% @post.errors.messages.each do |key,message| %>
  <%= content_tag :h4, "#{key}  #{message}" %>
<% end %>

app/views/posts/show.html.erb
  
<div class="post-box">
  <h3>
    <%= content_tag :span, @post.title, class:"post-title" %>
      by 
    <%= content_tag :span, @user.name, class:"post-author" %>
  </h3>
    <span class="comments_likes_count">
      <%= content_tag :small, "Comments: #{@post.comments_counter}, Likes: #{@post.likes_counter}" %>
    </span>
  <%= content_tag :p, @post.text %>

  <div class="one-row-field">
    <%= button_to 'Comment', "/comments/new/#{@post.id}", method: :get %>
    <%= button_to 'Like', "/likes/create/#{@post.id}", method: :get %>
  </div>
</div>

</div class="comments-box">  
  <ul class="commemts-list">
    <% @comments.each do |comment|%>
      <li class="comment-item">
        <%= content_tag :span, comment.user.name, class:"comment-author-name" %>
        <%= content_tag :span, comment.text %>
      </li>
    <% end %>
  </ul>
</div>  

app/views/users/index.html.erb
 <ul class="user-list">
   <% @users.each do |user| %>
      <li class="user-item">
        <%= image_tag user.photo, alt: "User Photo", class:"user-photo" %>
        <a class="user-info label-link" href=<%="/users/#{user.id}"%>>
        <%= content_tag :h2, user.name %>
        </a>
        <%= content_tag :p, "Number of posts: #{user.posts_counter}" %>
      </li>
  <% end %>
</table>

app/views/users/show.html.erb
<div class="user-item">
  <%= image_tag @user.photo,alt: "User Photo", class:"user-photo" %>
  <div class="user-info">
    <%= content_tag :h2, @user.name %>
    <%= content_tag :p, "Number of posts: #{@user.posts_counter}" %>
  </div>
</div>

<div class="user-bio">
  <%= content_tag :h4, 'Bio' %>
  <%= content_tag :p, @user.bio %>
</div>

<%= content_tag :h4, 'RECENT POSTS', class:"post-list-title"%>

<% @user.recent_posts.each do |post|%>
<div class="user-bio">
      
  <a class="post-title label-link" href="<%= user_post_path(@user, post) %> ">
    <%= content_tag :h4, post.title %>
  </a>  
  <%= content_tag :p, post.text.truncate(100)%>
  <p>
    <%= content_tag :small, "Comments: #{post.comments_counter}, Likes: #{post.likes_counter}" %>
  </p>
</div>
      
    <%end%>
    <%= link_to 'Show all Posts', user_posts_path(@user), class: 'post-list-title' %>